#!/usr/bin/env bash
#
# Generate the local adapter and command files for one or more agent tools.
#
#   scripts/sdd-onboard.sh claude cursor copilot gemini codex
#   scripts/sdd-onboard.sh --check copilot

set -euo pipefail

if root=$(git rev-parse --show-toplevel 2>/dev/null); then
  cd "$root"
fi

marker='Generated by scripts/sdd-onboard.sh; rerun it to update.'
check=0
tools=()

die() { echo "sdd-onboard: $1" >&2; exit "${2:-1}"; }

while [ "$#" -gt 0 ]; do
  case "$1" in
    --check|-c) check=1 ;;
    --help|-h)
      sed -n '2,/^$/s/^# \{0,1\}//p' "$0"
      exit 0
      ;;
    claude|cursor|copilot|gemini|codex) tools+=("$1") ;;
    *) die "unsupported tool '$1' (use claude, cursor, copilot, gemini or codex)" 2 ;;
  esac
  shift
done

[ "${#tools[@]}" -gt 0 ] || die "pass at least one tool: claude, cursor, copilot, gemini or codex" 2
[ -f AGENTS.md ] || die "AGENTS.md not found" 2
[ -d docs/commands ] || die "docs/commands not found" 2

shopt -s nullglob

stage=$(mktemp -d)
trap 'rm -rf "$stage"' EXIT

rule_block() {
  sed -n '/<!-- sdd:rule1:start -->/,/<!-- sdd:rule1:end -->/p' AGENTS.md
}

description() {
  local file=$1 name
  name=$(basename "$file" .md)
  printf 'Follow the /sdd-%s workflow' "$name"
}

argument_hint() {
  local value
  value=$(sed -n 's/^Argument:[[:space:]]*//p' "$1" | head -n1)
  printf '%s' "${value:-optional input}"
}

# How much reasoning a command is worth, read from its own workflow file:
# `Reasoning: high` on a line of its own, with any rationale after it. A command
# that does not say defaults to standard.
#
# A tier, never a model name. Naming "Claude Opus 5" in eleven workflow files is
# eleven files to edit the day it is superseded, in every repository that
# inherited them — and a workflow file is meant to outlive a vendor's catalogue.
reasoning() {
  local value
  value=$(sed -n 's/^Reasoning:[[:space:]]*//p' "$1" | head -n1 | awk '{ print $1 }')
  printf '%s' "${value:-standard}"
}

upper() { printf '%s' "$1" | tr '[:lower:]-' '[:upper:]_'; }

# A model from .sdd/models.yml: one flat table per tool. Kept flat so this reads
# it with awk and the generator needs nothing installed.
config_model() {
  local file=.sdd/models.yml
  [ -f "$file" ] || return 0
  awk -v block="$1" -v key="$2" '
    $0 ~ "^" block ":"      { inb = 1; next }
    inb && /^[^[:space:]#]/ { exit }
    inb {
      line = $0; sub(/#.*/, "", line)
      if (match(line, /^[[:space:]]+[A-Za-z_]+:/)) {
        k = line; sub(/^[[:space:]]+/, "", k); sub(/:.*/, "", k)
        v = line; sub(/^[[:space:]]+[A-Za-z_]+:[[:space:]]*/, "", v)
        gsub(/^[[:space:]]+|[[:space:]]+$/, "", v)
        gsub(/^"|"$|^'"'"'|'"'"'$/, "", v)
        if (k == key) { print v; exit }
      }
    }' "$file"
}

# The tier, resolved to whatever this repository runs — per tool, because the
# catalogues do not match. Claude Code takes its own aliases, Copilot takes the
# name as the model picker shows it, and an account without that model gets a
# reference to something that does not exist.
#
# Most specific first:
#   SDD_MODEL_CLAUDE_HIGH   one tool, one tier, this invocation only
#   SDD_MODEL_HIGH          every tool, this invocation only
#   .sdd/models.yml         the committed table — where a team sets this
#   the defaults below      what a repository gets before it edits anything
model_for() {
  local tier=$1 tool=$2 specific generic value
  specific=$(printf 'SDD_MODEL_%s_%s' "$(upper "$tool")" "$(upper "$tier")")
  generic=$(printf 'SDD_MODEL_%s' "$(upper "$tier")")

  if [ -n "${!specific:-}" ]; then printf '%s' "${!specific}"; return; fi
  if [ -n "${!generic:-}" ]; then printf '%s' "${!generic}"; return; fi

  value=$(config_model "$tool" "$tier")
  if [ -n "$value" ]; then printf '%s' "$value"; return; fi

  case "$tool:$tier" in
    claude:high)        printf 'opus' ;;
    claude:mechanical)  printf 'haiku' ;;
    claude:*)           printf 'sonnet' ;;
    copilot:high)       printf 'Claude Opus 5' ;;
    copilot:mechanical) printf 'Claude Haiku 4.5' ;;
    copilot:*)          printf 'Claude Sonnet 5' ;;
    *)                  printf '' ;;
  esac
}

# What every adapter says about the model. Nothing generated here sets one: the
# tier and its suggestion are reported to the user, who confirms or changes it
# before the work starts. A model chosen for someone silently is a cost and a
# quality decision taken out of their hands, and the tools disagree about which
# models even exist.
#
# With no table for that tool it names the tier and suggests nothing, rather
# than a model nobody chose.
model_note() {
  local tier=$1 tool=$2 model
  model=$(model_for "$tier" "$tool")
  printf 'Before doing anything else, tell the user this workflow is rated `%s` reasoning' "$tier"
  [ -n "$model" ] && printf ', that the suggested model for it is **%s**' "$model"
  printf ', and which model you are currently running on. Then stop and wait: they confirm it or switch, and you continue on whatever they choose. Never refuse to run on the model they pick, and never change it yourself.'
}

escape_double_quotes() {
  sed 's/\\/\\\\/g; s/"/\\"/g'
}

# One value from a file's own YAML frontmatter, e.g. `description` or `applyTo`.
frontmatter_field() {
  local file=$1 key=$2
  awk -v key="$key" '
    /^---$/ { c++; next }
    c == 1 && $0 ~ "^" key ":" { sub("^" key ":[ \t]*", ""); gsub(/^"|"$/, ""); print; exit }
  ' "$file"
}

# Everything after a file's own frontmatter, unchanged.
body_after_frontmatter() {
  awk '/^---$/ { c++; next } c >= 2 { print }' "$1"
}

# A managed file whose frontmatter must stay on line 1 gets the marker after
# its closing `---` instead of before it.
inject_marker() {
  local file=$1
  awk -v marker="<!-- $marker -->" '
    /^---$/ { c++; print; if (c == 2) { print ""; print marker; print "" }; next }
    { print }
  ' "$file"
}

# Marker plus body, for a file whose original frontmatter was replaced by a
# freshly generated one rather than copied.
marker_then_body() {
  printf '\n<!-- %s -->\n\n' "$marker"
  body_after_frontmatter "$1"
}

write_adapter() {
  local tool=$1 target
  case "$tool" in
    claude)
      target=CLAUDE.md
      {
        printf '<!-- %s -->\n\n@AGENTS.md\n\n' "$marker"
        printf 'Read `AGENTS.md` at the repository root and follow it. Keep project content there, not here.\n\n'
        rule_block
      } > "$stage/$target"
      ;;
    gemini)
      target=GEMINI.md
      {
        printf '<!-- %s -->\n\n' "$marker"
        printf 'Read `AGENTS.md` at the repository root and follow it. Keep project content there, not here.\n\n'
        rule_block
      } > "$stage/$target"
      ;;
    codex)
      # Codex already reads AGENTS.md at the repository root, so there is no
      # second instructions file to write and nothing to keep in step with it.
      return 0
      ;;
    copilot)
      target=.github/copilot-instructions.md
      mkdir -p "$stage/.github"
      {
        printf '<!-- %s -->\n\n' "$marker"
        printf 'Read `AGENTS.md` at the repository root and follow it. Keep project content there, not here.\n\n'
        rule_block
      } > "$stage/$target"
      ;;
    cursor)
      target=.cursor/rules/00-spec-first.mdc
      mkdir -p "$stage/.cursor/rules"
      {
        printf '%s\n' '---' 'description: Enforce the repository SDD workflow' 'alwaysApply: true' '---' ''
        printf '<!-- %s -->\n\n' "$marker"
        printf 'Read `AGENTS.md` at the repository root and follow it. Keep project content there, not here.\n\n'
        rule_block
      } > "$stage/$target"
      ;;
  esac
}

write_commands() {
  local tool=$1 file name target desc hint tier
  for file in docs/commands/*.md; do
    name=$(basename "$file" .md)
    desc=$(description "$file")
    hint=$(argument_hint "$file")
    tier=$(reasoning "$file")
    case "$tool" in
      claude)
        target=".claude/commands/sdd-$name.md"
        mkdir -p "$stage/.claude/commands"
        {
          printf '%s\n' '---'
          printf 'description: "%s"\n' "$(printf '%s' "$desc" | escape_double_quotes)"
          printf 'argument-hint: "%s"\n' "$(printf '%s' "$hint" | escape_double_quotes)"
          printf '%s\n\n' '---'
          printf '<!-- %s -->\n\n' "$marker"
          printf 'Read `docs/commands/%s.md` and follow it.\n\n%s\n\nInput: $ARGUMENTS\n' \
            "$name" "$(model_note "$tier" "$tool")"
        } > "$stage/$target"
        ;;
      cursor)
        target=".cursor/commands/sdd-$name.md"
        mkdir -p "$stage/.cursor/commands"
        printf '<!-- %s -->\n\nRead `docs/commands/%s.md` and follow it.\n\n%s\n\nInput: $ARGUMENTS\n' \
          "$marker" "$name" "$(model_note "$tier" "$tool")" > "$stage/$target"
        ;;
      copilot)
        target=".github/prompts/sdd-$name.prompt.md"
        mkdir -p "$stage/.github/prompts"
        {
          printf '%s\n' '---'
          printf 'mode: agent\n'
          printf 'description: "%s"\n' "$(printf '%s' "$desc" | escape_double_quotes)"
          printf 'argument-hint: "%s"\n' "$(printf '%s' "$hint" | escape_double_quotes)"
          printf '%s\n\n' '---'
          printf '<!-- %s -->\n\n' "$marker"
          printf 'Read `docs/commands/%s.md` and follow it.\n\n%s\n\nInput: ${input:args}\n' \
            "$name" "$(model_note "$tier" "$tool")"
        } > "$stage/$target"
        ;;
      gemini)
        target=".gemini/commands/sdd-$name.toml"
        mkdir -p "$stage/.gemini/commands"
        {
          printf '# %s\n' "$marker"
          printf 'description = "%s"\n' "$(printf '%s' "$desc" | escape_double_quotes)"
          printf 'prompt = "Read docs/commands/%s.md and follow it.\\n\\n%s\\n\\nInput: {{args}}"\n' \
            "$name" "$(model_note "$tier" "$tool" | escape_double_quotes)"
        } > "$stage/$target"
        ;;
      codex)
        # Codex reads AGENTS.md natively; its custom prompts are plain markdown
        # with no model field, so the tier travels in the body.
        target=".codex/prompts/sdd-$name.md"
        mkdir -p "$stage/.codex/prompts"
        {
          printf '<!-- %s -->\n\n' "$marker"
          printf '# /sdd-%s — %s\n\n' "$name" "$desc"
          printf 'Read `docs/commands/%s.md` and follow it.\n\n' "$name"
          printf '%s\n\n' "$(model_note "$tier" "$tool")"
          printf 'Input: $ARGUMENTS\n'
        } > "$stage/$target"
        ;;
    esac
  done
}

# One subagent or chat mode per file under docs/agents/. Tools with no such
# concept (cursor, gemini) are skipped rather than approximated.
write_agents() {
  local tool=$1 file slug desc target
  for file in docs/agents/*.md; do
    slug=$(basename "$file" .md)
    desc=$(frontmatter_field "$file" description)
    case "$tool" in
      claude)
        target=".claude/agents/$slug.md"
        mkdir -p "$stage/.claude/agents"
        {
          printf '%s\n' '---'
          printf 'name: %s\n' "$slug"
          printf 'description: "%s"\n' "$(printf '%s' "$desc" | escape_double_quotes)"
          printf '%s\n' '---'
          marker_then_body "$file"
        } > "$stage/$target"
        ;;
      copilot)
        target=".github/chatmodes/$slug.chatmode.md"
        mkdir -p "$stage/.github/chatmodes"
        {
          printf '%s\n' '---'
          printf 'description: "%s"\n' "$(printf '%s' "$desc" | escape_double_quotes)"
          printf '%s\n' '---'
          marker_then_body "$file"
        } > "$stage/$target"
        ;;
    esac
  done
}

# One skill directory per docs/skills/<slug>/SKILL.md, copied as-is: its own
# name/description frontmatter is already what a native skill directory reads.
write_skills() {
  local tool=$1 dir slug target
  for dir in docs/skills/*/; do
    [ -f "${dir}SKILL.md" ] || continue
    slug=$(basename "$dir")
    case "$tool" in
      claude) target=".claude/skills/$slug/SKILL.md" ;;
      copilot) target=".github/skills/$slug/SKILL.md" ;;
      *) continue ;;
    esac
    mkdir -p "$stage/$(dirname "$target")"
    inject_marker "${dir}SKILL.md" > "$stage/$target"
  done
}

# One scoped rule per file under docs/standards/, translated to the glob field
# each tool reads (Copilot `applyTo`, Cursor `globs`). Tools with no per-file
# scoping (claude, gemini) are skipped: an always-on standard belongs in AGENTS.md.
write_standards() {
  local tool=$1 file slug desc applyto target
  for file in docs/standards/*.md; do
    slug=$(basename "$file" .md)
    desc=$(frontmatter_field "$file" description)
    applyto=$(frontmatter_field "$file" applyTo)
    case "$tool" in
      copilot)
        target=".github/instructions/$slug.instructions.md"
        mkdir -p "$stage/.github/instructions"
        {
          printf '%s\n' '---'
          printf 'description: "%s"\n' "$(printf '%s' "$desc" | escape_double_quotes)"
          printf 'applyTo: "%s"\n' "$(printf '%s' "$applyto" | escape_double_quotes)"
          printf '%s\n' '---'
          marker_then_body "$file"
        } > "$stage/$target"
        ;;
      cursor)
        target=".cursor/rules/$slug.mdc"
        mkdir -p "$stage/.cursor/rules"
        {
          printf '%s\n' '---'
          printf 'description: "%s"\n' "$(printf '%s' "$desc" | escape_double_quotes)"
          printf 'globs: "%s"\n' "$(printf '%s' "$applyto" | escape_double_quotes)"
          printf '%s\n' 'alwaysApply: false'
          printf '%s\n' '---'
          marker_then_body "$file"
        } > "$stage/$target"
        ;;
    esac
  done
}

# The PreToolUse hook that routes a shell command through
# scripts/sdd-compact.sh before the agent runs it. Every target below is
# gitignored: a hook is a developer's local wiring, and the tool it wires is
# scripts/sdd-hook.sh, which is not.
#
# The management marker rides in a "_generatedBy" key, since JSON has no
# comments. A file here that lacks it was written by someone else, and
# install_generated refuses to overwrite it rather than merging JSON blind.

# An absolute path, because a hook does not always run from the repository root
# — a backgrounded subagent does not — and a relative one dies there with "No
# such file or directory" and no compaction. Every target is gitignored, so a
# path that only works on this machine is the right thing to write. One needing
# quotes would have to survive shell and JSON escaping both: fall back to the
# relative form rather than emit a file the tool rejects whole.
hook_command() {
  local path="$PWD/scripts/sdd-hook.sh"
  case $path in
    *[!A-Za-z0-9/._-]*) path=scripts/sdd-hook.sh ;;
  esac
  printf 'bash %s %s' "$path" "$1"
}

write_hooks() {
  local tool=$1 target event
  case "$tool" in
    claude)  target=.claude/settings.local.json;    event=PreToolUse ;;
    copilot) target=.github/hooks/sdd-compact.json; event=PreToolUse ;;
    codex)   target=.codex/hooks.json;              event=PreToolUse ;;
    cursor)  target=.cursor/hooks.json;             event=preToolUse ;;
    gemini)  target=.gemini/settings.json;          event=BeforeTool ;;
    *) return 0 ;;
  esac

  mkdir -p "$stage/$(dirname "$target")"
  {
    printf '{\n'
    printf '  "_generatedBy": "%s",\n' "$marker"
    printf '  "hooks": {\n'
    printf '    "%s": [\n' "$event"
    printf '      {\n'
    # Claude Code nests its commands under a matcher and rejects the file
    # outright without one. VS Code reads that shape too — it parses Claude's
    # format and ignores the matcher — but the other three take the command
    # directly, and a key they do not know is one more thing to be wrong about.
    if [ "$tool" = claude ]; then
      printf '        "matcher": "Bash",\n'
      printf '        "hooks": [\n'
      printf '          {\n'
      printf '            "type": "command",\n'
      printf '            "command": "%s"\n' "$(hook_command claude)"
      printf '          }\n'
      printf '        ]\n'
    else
      printf '        "type": "command",\n'
      printf '        "command": "%s"' "$(hook_command "$tool")"
      # Codex reads the OS-specific spelling rather than the shared one.
      if [ "$tool" = codex ]; then
        printf ',\n        "bash": "%s"' "$(hook_command codex)"
      fi
      printf '\n'
    fi
    printf '      }\n'
    printf '    ]\n'
    printf '  }\n'
    printf '}\n'
  } > "$stage/$target"
}

install_generated() {
  local source=$1 target=${1#"$stage"/}
  if [ -f "$target" ] && ! grep -Fq "$marker" "$target"; then
    die "$target exists and is not managed by this script; move it or merge it manually"
  fi
  if [ "$check" -eq 1 ]; then
    if ! cmp -s "$source" "$target"; then
      echo "out of date: $target" >&2
      return 1
    fi
    return 0
  fi
  mkdir -p "$(dirname "$target")"
  cp "$source" "$target"
  echo "generated: $target"
}

for tool in "${tools[@]}"; do
  write_adapter "$tool"
  write_commands "$tool"
  write_agents "$tool"
  write_skills "$tool"
  write_standards "$tool"
  write_hooks "$tool"
done

failed=0
while IFS= read -r source; do
  install_generated "$source" || failed=1
done < <(find "$stage" -type f | sort)

if [ "$failed" -ne 0 ]; then
  die "generated files differ; run without --check to update them"
fi

if [ "$check" -eq 1 ]; then
  echo "Agent adapters and commands are up to date."
fi