#!/usr/bin/env bash
#
# Generate the local adapter and command files for one or more agent tools.
#
#   scripts/sdd-onboard.sh claude cursor copilot gemini
#   scripts/sdd-onboard.sh --check copilot

set -euo pipefail

if root=$(git rev-parse --show-toplevel 2>/dev/null); then
  cd "$root"
fi

marker='Generated by scripts/sdd-onboard.sh; rerun it to update.'
check=0
tools=()

die() { echo "sdd-onboard: $1" >&2; exit "${2:-1}"; }

while [ "$#" -gt 0 ]; do
  case "$1" in
    --check|-c) check=1 ;;
    --help|-h)
      sed -n '2,/^$/s/^# \{0,1\}//p' "$0"
      exit 0
      ;;
    claude|cursor|copilot|gemini) tools+=("$1") ;;
    *) die "unsupported tool '$1' (use claude, cursor, copilot or gemini)" 2 ;;
  esac
  shift
done

[ "${#tools[@]}" -gt 0 ] || die "pass at least one tool: claude, cursor, copilot or gemini" 2
[ -f AGENTS.md ] || die "AGENTS.md not found" 2
[ -d docs/commands ] || die "docs/commands not found" 2

stage=$(mktemp -d)
trap 'rm -rf "$stage"' EXIT

rule_block() {
  sed -n '/<!-- sdd:rule1:start -->/,/<!-- sdd:rule1:end -->/p' AGENTS.md
}

description() {
  local file=$1 name
  name=$(basename "$file" .md)
  printf 'Follow the /sdd-%s workflow' "$name"
}

argument_hint() {
  local value
  value=$(sed -n 's/^Argument:[[:space:]]*//p' "$1" | head -n1)
  printf '%s' "${value:-optional input}"
}

escape_double_quotes() {
  sed 's/\\/\\\\/g; s/"/\\"/g'
}

write_adapter() {
  local tool=$1 target
  case "$tool" in
    claude)
      target=CLAUDE.md
      {
        printf '<!-- %s -->\n\n@AGENTS.md\n\n' "$marker"
        printf 'Read `AGENTS.md` at the repository root and follow it. Keep project content there, not here.\n\n'
        rule_block
      } > "$stage/$target"
      ;;
    gemini)
      target=GEMINI.md
      {
        printf '<!-- %s -->\n\n' "$marker"
        printf 'Read `AGENTS.md` at the repository root and follow it. Keep project content there, not here.\n\n'
        rule_block
      } > "$stage/$target"
      ;;
    copilot)
      target=.github/copilot-instructions.md
      mkdir -p "$stage/.github"
      {
        printf '<!-- %s -->\n\n' "$marker"
        printf 'Read `AGENTS.md` at the repository root and follow it. Keep project content there, not here.\n\n'
        rule_block
      } > "$stage/$target"
      ;;
    cursor)
      target=.cursor/rules/00-spec-first.mdc
      mkdir -p "$stage/.cursor/rules"
      {
        printf '%s\n' '---' 'description: Enforce the repository SDD workflow' 'alwaysApply: true' '---' ''
        printf '<!-- %s -->\n\n' "$marker"
        printf 'Read `AGENTS.md` at the repository root and follow it. Keep project content there, not here.\n\n'
        rule_block
      } > "$stage/$target"
      ;;
  esac
}

write_commands() {
  local tool=$1 file name target desc hint
  for file in docs/commands/*.md; do
    name=$(basename "$file" .md)
    desc=$(description "$file")
    hint=$(argument_hint "$file")
    case "$tool" in
      claude)
        target=".claude/commands/sdd-$name.md"
        mkdir -p "$stage/.claude/commands"
        {
          printf '%s\n' '---'
          printf 'description: "%s"\n' "$(printf '%s' "$desc" | escape_double_quotes)"
          printf 'argument-hint: "%s"\n' "$(printf '%s' "$hint" | escape_double_quotes)"
          printf '%s\n\n' '---'
          printf '<!-- %s -->\n\n' "$marker"
          printf 'Read `docs/commands/%s.md` and follow it.\n\nInput: $ARGUMENTS\n' "$name"
        } > "$stage/$target"
        ;;
      cursor)
        target=".cursor/commands/sdd-$name.md"
        mkdir -p "$stage/.cursor/commands"
        printf '<!-- %s -->\n\nRead `docs/commands/%s.md` and follow it.\n\nInput: $ARGUMENTS\n' \
          "$marker" "$name" > "$stage/$target"
        ;;
      copilot)
        target=".github/prompts/sdd-$name.prompt.md"
        mkdir -p "$stage/.github/prompts"
        printf '<!-- %s -->\n\nRead `docs/commands/%s.md` and follow it.\n\nInput: ${input:args}\n' \
          "$marker" "$name" > "$stage/$target"
        ;;
      gemini)
        target=".gemini/commands/sdd-$name.toml"
        mkdir -p "$stage/.gemini/commands"
        {
          printf '# %s\n' "$marker"
          printf 'description = "%s"\n' "$(printf '%s' "$desc" | escape_double_quotes)"
          printf 'prompt = "Read docs/commands/%s.md and follow it.\\n\\nInput: {{args}}"\n' "$name"
        } > "$stage/$target"
        ;;
    esac
  done
}

install_generated() {
  local source=$1 target=${1#"$stage"/}
  if [ -f "$target" ] && ! grep -Fq "$marker" "$target"; then
    die "$target exists and is not managed by this script; move it or merge it manually"
  fi
  if [ "$check" -eq 1 ]; then
    if ! cmp -s "$source" "$target"; then
      echo "out of date: $target" >&2
      return 1
    fi
    return 0
  fi
  mkdir -p "$(dirname "$target")"
  cp "$source" "$target"
  echo "generated: $target"
}

for tool in "${tools[@]}"; do
  write_adapter "$tool"
  write_commands "$tool"
done

failed=0
while IFS= read -r source; do
  install_generated "$source" || failed=1
done < <(find "$stage" -type f | sort)

if [ "$failed" -ne 0 ]; then
  die "generated files differ; run without --check to update them"
fi

if [ "$check" -eq 1 ]; then
  echo "Agent adapters and commands are up to date."
fi