#!/usr/bin/env bash
# Diagnose local SDD setup without installing tools or contacting remotes.

set -u

if root=$(git rev-parse --show-toplevel 2>/dev/null); then
  cd "$root"
fi

failed=0
warnings=0
marker='Generated by scripts/sdd-onboard.sh; rerun it to update.'

pass() { printf 'ok: %s\n' "$1"; }
warn() { printf 'warning: %s\n' "$1" >&2; warnings=$((warnings + 1)); }
fail() { printf 'error: %s\n' "$1" >&2; failed=$((failed + 1)); }

config_field() {
  sed -n '/^spec_repo:/,/^[^[:space:]#]/p' .sdd/config.yml \
    | sed -n "s/^[[:space:]][[:space:]]*$1:[[:space:]]*//p" \
    | head -n1 \
    | sed -e 's/[[:space:]]*#.*$//' -e 's/\r$//' -e 's/^"//' -e 's/"$//' -e "s/^'//" -e "s/'\$//" -e 's/[[:space:]]*$//'
}

for command in bash git sed awk grep find sort mktemp diff cmp; do
  command -v "$command" >/dev/null 2>&1 \
    && pass "$command is available" \
    || fail "$command is required but unavailable"
done

for file in AGENTS.md docs/commands scripts/sdd-onboard.sh scripts/sdd-check.sh \
  scripts/sdd-lib.sh scripts/sdd-compact.sh scripts/sdd-recall.sh scripts/sdd-hook.sh \
  scripts/sdd-upgrade.sh .sdd/manifest.yml; do
  [ -e "$file" ] && pass "$file exists" || fail "$file is missing"
done

# Where this repository's scaffolding came from. Without it an upgrade has no
# baseline to tell a local edit from a file that is simply old.
if [ -f .sdd/template.yml ]; then
  pass "template: $(sed -n 's/^version:[[:space:]]*//p' .sdd/template.yml | head -n1) from $(sed -n 's/^source:[[:space:]]*//p' .sdd/template.yml | head -n1)"
  [ -f .sdd/template.lock ] \
    && pass '.sdd/template.lock records what the template delivered' \
    || warn '.sdd/template.lock is missing; run scripts/sdd-upgrade.sh --adopt'
else
  printf 'note: no .sdd/template.yml, so this repository records no template version. See docs/commands/upgrade.md.\n'
fi

# A hook that exits non-zero takes the agent's turn down with it, so the one
# thing worth checking here is that a payload it cannot read is survivable.
if [ -f scripts/sdd-hook.sh ]; then
  if printf 'not a payload' | bash scripts/sdd-hook.sh claude > /dev/null 2>&1; then
    pass 'the rewrite hook fails open on an unreadable payload'
  else
    fail 'the rewrite hook exits non-zero on an unreadable payload'
  fi
fi

if [ -f .github/hooks/sdd-compact.json ] && [ -f .claude/settings.local.json ]; then
  printf 'note: VS Code loads .github/hooks/ and .claude/settings.local.json both, so the hook runs twice per command; the second call is a no-op.\n'
fi

# A repository with no subagents defined does every read in the main thread, and
# pays for it again on every call that follows.
if [ -d docs/agents ]; then
  if find docs/agents -maxdepth 1 -name '*.md' | grep -q .; then
    pass "$(find docs/agents -maxdepth 1 -name '*.md' | wc -l | tr -d ' ') subagent(s) defined in docs/agents/"
  else
    warn 'docs/agents/ is empty, so nothing is ever delegated; see docs/skills/delegating-exploration/'
  fi
fi

shell_failed=0
while IFS= read -r script; do
  bash -n "$script" || shell_failed=1
done < <(find scripts -type f -name '*.sh' | sort)
[ "$shell_failed" -eq 0 ] && pass 'shell scripts parse' || fail 'one or more shell scripts do not parse'

set --
for candidate in \
  'claude:CLAUDE.md' \
  'cursor:.cursor/rules/00-spec-first.mdc' \
  'copilot:.github/copilot-instructions.md' \
  'gemini:GEMINI.md'; do
  tool=${candidate%%:*}
  target=${candidate#*:}
  [ -f "$target" ] || continue
  if grep -Fq "$marker" "$target"; then
    set -- "$@" "$tool"
    git check-ignore -q "$target" \
      && pass "$target is ignored" \
      || warn "$target is generated but not ignored; confirm it is intentionally shared"
  else
    warn "$target exists but is not managed by scripts/sdd-onboard.sh"
  fi
done

if [ "$#" -eq 0 ]; then
  printf 'note: no managed agent adapters found; run scripts/sdd-onboard.sh for the tools used here.\n'
elif bash scripts/sdd-onboard.sh --check "$@" >/dev/null; then
  pass "managed agent adapters are current ($*)"
else
  fail "managed agent adapters are stale; run scripts/sdd-onboard.sh $*"
fi

# The shape of a spec id, which every repository declares and this one owns.
if [ -f .sdd/config.yml ] && grep -q '^spec_id:' .sdd/config.yml; then
  id_pattern=$(sed -n '/^spec_id:/,/^[^[:space:]#]/p' .sdd/config.yml \
    | sed -n 's/^[[:space:]][[:space:]]*pattern:[[:space:]]*//p' | head -n1 \
    | sed -e "s/^'//" -e "s/'\$//" -e 's/[[:space:]]*$//')
  case "$id_pattern" in
    ''|*'<'*) fail 'spec_id.pattern is empty or still a placeholder' ;;
    *) pass "spec ids match '$id_pattern'" ;;
  esac
fi

# Only a repository that consumes a Spec Repository has one to check.
if [ -f .sdd/config.yml ] && grep -q '^spec_repo:' .sdd/config.yml; then
  if grep -qE '^spec_repo:[[:space:]]*none[[:space:]]*(#.*)?$' .sdd/config.yml; then
    pass 'spec_repo: none; this repository owns its specs'
  else
    path=$(config_field path)
    remote=$(config_field remote)
    ref=$(config_field ref)
    specs_dir=$(config_field specs_dir)

    for pair in "ref:$ref" "specs_dir:$specs_dir"; do
      case "${pair#*:}" in
        ''|*'<'*) fail "${pair%%:*} is empty or still a placeholder" ;;
        *) pass "${pair%%:*} is configured" ;;
      esac
    done

    case "$path" in ''|*'<'*) path="" ;; esac
    case "$remote" in ''|*'<'*) remote="" ;; esac

    path_valid=0
    if [ -n "$path" ] && git -C "$path" rev-parse --git-dir >/dev/null 2>&1; then
      path_valid=1
      pass "path is a git repository: $path"
    elif [ -n "$path" ]; then
      warn "path is not a git repository: $path"
    fi

    if [ -n "$remote" ]; then
      pass 'remote is configured (reachability not checked)'
      if [ "$path_valid" -eq 1 ]; then
        path_remote=$(git -C "$path" remote get-url origin 2>/dev/null || true)
        if [ "$path_remote" = "$remote" ]; then
          pass 'path origin matches remote and can be used as its cache'
        else
          warn "path origin '$path_remote' does not match remote '$remote'; sync will ignore path"
        fi
      fi
    elif [ "$path_valid" -eq 1 ]; then
      pass 'path is the explicit local-only spec authority'
    else
      fail 'neither remote nor a valid local-only path is configured'
    fi
  fi
fi

if [ -f scripts/spec-hash.sh ]; then
  if command -v shasum >/dev/null 2>&1 || command -v sha256sum >/dev/null 2>&1; then
    pass 'a SHA-256 command is available'
  else
    fail 'spec-hash.sh needs shasum or sha256sum'
  fi
fi

printf '\n%d error(s), %d warning(s).\n' "$failed" "$warnings"
[ "$failed" -eq 0 ]