#!/usr/bin/env bash
#
# specs/INDEX.md is a derived view of the spec headers, never a second place
# to type a status. Whoever edited it by hand and whoever edited the header
# last used to disagree; this is the one place that renders the table, so they
# cannot.
#
#   scripts/spec-index.sh           # rewrite specs/INDEX.md in place
#   scripts/spec-index.sh --check   # fail if specs/INDEX.md is out of date
#
# See docs/lifecycle.md.

set -euo pipefail

# Run from the repository root whatever the caller's directory is.
if root=$(git rev-parse --show-toplevel 2>/dev/null); then
  cd "$root"
fi

# One bold-key field, first match, trailing HTML comment and whitespace stripped.
field() {
  sed -n "s/^- \*\*$2:\*\*[[:space:]]*//p" "$1" \
    | head -n1 \
    | sed -e 's/<!--.*-->//' -e 's/[[:space:]]*$//'
}

# "# Spec 014 — Password reset" -> "Password reset". Whatever sits after the
# first em dash, so it does not care how the number is written.
title_of() {
  head -n1 "$1" | sed -E 's/^#[[:space:]]*[^—]*—[[:space:]]*//'
}

rows_of() {
  shopt -s nullglob
  local dir spec slug title status owner consumers updated
  for dir in specs/*/; do
    spec="${dir%/}/spec.md"
    [ -f "$spec" ] || continue
    slug=$(basename "$dir")
    title=$(title_of "$spec")
    status=$(field "$spec" Status)
    owner=$(field "$spec" Owner)
    consumers=$(field "$spec" Consumers)
    updated=$(field "$spec" Updated)
    printf '| [`%s`](%s/spec.md) — %s | %s | %s | %s | %s |\n' \
      "$slug" "$slug" "$title" "$status" "$owner" "$consumers" "$updated"
  done
}

render() {
  cat <<'HEADER'
# Specs

<!-- Regenerated by scripts/spec-index.sh, not maintained by hand. Where
     this file and a spec header disagree, the spec header wins. -->

Every specification in this repository. A development repository builds against
a published spec — `approved`, or `done` once it has been delivered — see
`docs/lifecycle.md`.

| Spec | Status | Owner | Consumers | Updated |
| --- | --- | --- | --- | --- |
HEADER

  local rows
  rows=$(rows_of)
  if [ -n "$rows" ]; then
    printf '%s\n' "$rows" | sort
  else
    printf '\n<!-- No specs yet. /sdd-specify writes the first one and its row. -->\n'
  fi
}

case "${1:-}" in
  --check|-c)
    tmp=$(mktemp)
    trap 'rm -f "$tmp"' EXIT
    render >"$tmp"
    if diff -u specs/INDEX.md "$tmp" >/dev/null 2>&1; then
      echo "specs/INDEX.md matches the spec headers."
    else
      echo "::error file=specs/INDEX.md::out of date — regenerate with scripts/spec-index.sh"
      diff -u specs/INDEX.md "$tmp" || true
      exit 1
    fi
    ;;
  --help|-h)
    awk 'NR > 1 && /^#/ { sub(/^#[[:space:]]?/, ""); print; next } NR > 1 { exit }' "$0"
    ;;
  "")
    render >specs/INDEX.md
    echo "specs/INDEX.md regenerated."
    ;;
  *)
    echo "spec-index: unknown option: $1" >&2
    exit 2
    ;;
esac
